---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland           # Wayland compositor
      - waybar             # Status bar
      - wofi               # App launcher
      - swaylock           # Screen locker
      - grim               # Screenshot tool (captures screen)
      - slurp              # Screenshot tool (selects region)
      - thunar             # File manager
      - btop               # Resource monitor
      - qt5-wayland        # Qt5 Wayland support
      - qt6-wayland        # Qt6 Wayland support
      - xdg-desktop-portal-hyprland # Portal for Hyprland (needed by apps)
      - rofi               # Rofi theme selector (alternative to wofi for some)
      - mpv                # Media player (often used for screenshots/recording previews)
      - firefox            # Brave is mentioned, but Firefox is a solid default
      - discord            # From screenshot
      - spotify-launcher   # From screenshot (often needs AUR)
      - telegram-desktop   # From screenshot
      - blueman            # Bluetooth manager
      - xorg-xwayland      # Compatibility layer for Xorg applications
      - polkit-kde-agent   # PolicyKit authentication agent (often needed for graphical sudo prompts)
      - pamixer            # For audio control
      - mako               # Notification daemon
      - cliphist           # Clipboard history
      - pavucontrol        # PulseAudio/PipeWire volume control
      - sddm               # login screen
      # catpuccin sddm dependencies
      - qt6-svg
      - qt6-declarative
      - qt5-quickcontrols2
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
  become: false

- name: enable and start sddm
  systemd:
    name: sddm.service
    enabled: yes
    state: started
  beocme: true

- name: create config directories
  file:
    path: "/home/{{ target_user }}/{{ item.path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ target_user }}/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"

- name: ensure sddm themes directory exists
  file:
    path: "/usr/share/sddm/themes
    state: directory
    mode: '0755'

- name: download catpuccin sddm theme
  get_url: 
    url: https://github.com/catppuccin/sddm/releases/download/v1.0.0/catppuccin-frappe.zip
    dest: "/tmp/catpuccin-frappe.zip"
    mode: '0644'
  become: true

- name: unzip theme to themes directory
  unarchive:
    src: /tmp/catpuccin-frappe.zip
    dest: /usr/share/sddm/themes/
    remote_src: yes
    creates: /usr/share/sddm/themes/catpuccin-frappe

- name: create sddm config
  template:
    src: sddm.conf
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: '0644'