---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland
      - hyprcursor
      - waybar
      - wofi
      - grim
      - slurp
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - mako
      - hyprlock
      - cliphist
      - gnome-keyring
      - libsecret
      - seahorse
      - hypridle
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
    yay -S --noconfirm wlogout
    yay -S --noconfirm swww
    yay -S --noconfirm catppuccin-cursors-frappe
  become: false

- name: symlink dotfiles
  command: "stow .config -t /home/{{ ansible_user }} -d /home/{{ ansible_user }}/.config/dotfiles_source"
  args:
    chdir: "/home/{{ ansible_user }}/.config/dotfiles_source"
  become: yes
  register: stow_sddm_theme
  changed_when: "'LINK' in stow_sddm_theme.stdout or 'RESTOW' in stow_sddm_theme.stdout"

- name: remove unwanted session files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/usr/share/wayland-sessions/hyprland-uwsm.desktop"
