---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland
      - hyprcursor
      - waybar
      - wofi
      - grim
      - slurp
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - mako
      - hyprlock
      - cliphist
      - gnome-keyring
      - libsecret
      - seahorse
      - hypridle
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm --needed {{ item }}
  loop:
    - grimblast-git
    - light
    - wlogout
    - swww
    - catppuccin-cursors-frappe
  become: false

- name: run dotfile deployment playbook
  include_playbook: "/home/{{ ansible_user }}/dotfile_source/ansible/playbooks/deploy-dotfiles.yml"

- name: remove unwanted session files
  file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/usr/share/wayland-sessions/hyprland-uwsm.desktop"
