---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland
      - hyprcursor
      - waybar
      - wofi
      - grim
      - slurp
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - mako
      - hyprlock
      - cliphist
      - gnome-keyring
      - libsecret
      - seahorse
      - hypridle
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
    yay -S --noconfirm wlogout
    yay -S --noconfirm swww
    yay -S --noconfirm catppuccin-cursors-frappe
  become: false

- name: create config directories
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"

- name: remove unwanted session files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/usr/share/wayland-sessions/hyprland-uwsm.desktop"
