---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland           # Wayland compositor
      - waybar             # Status bar
      - wofi               # App launcher
      - swaylock           # Screen locker
      - grim               # Screenshot tool (captures screen)
      - slurp              # Screenshot tool (selects region)
      - thunar             # File manager
      - btop               # Resource monitor
      - qt5-wayland        # Qt5 Wayland support
      - qt6-wayland        # Qt6 Wayland support
      - xdg-desktop-portal-hyprland # Portal for Hyprland (needed by apps)
      - rofi               # Rofi theme selector (alternative to wofi for some)
      - mpv                # Media player (often used for screenshots/recording previews)
      - firefox            # Brave is mentioned, but Firefox is a solid default
      - discord            # From screenshot
      - spotify-launcher   # From screenshot (often needs AUR)
      - telegram-desktop   # From screenshot
      - blueman            # Bluetooth manager
      - xorg-xwayland      # Compatibility layer for Xorg applications
      - polkit-kde-agent   # PolicyKit authentication agent (often needed for graphical sudo prompts)
      - pamixer            # For audio control
      - mako               # Notification daemon
      - cliphist           # Clipboard history
      - pavucontrol        # PulseAudio/PipeWire volume control
    state: present
    extra_args: "--noconfirm"


- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
  become: false

- name: create config directories
  file:
    path: "/home/{{ target_user }}/{{ item.path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_filetree: "../templates"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ target_user }}/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  with_filetree: "../templates"
  when: item.state == "file"


