---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland
      - hyprcursor
      - waybar
      - wofi
      - grim
      - slurp
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - mako
      - hyprlock
      - cliphist
      - gnome-keyring
      - libsecret
      - seahorse
      - hypridle
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm --needed {{ item }}
  loop:
    - grimblast-git
    - light
    - wlogout
    - swww
    - catppuccin-cursors-frappe
  become: false

- name: symlink dotfiles
  command: "stow {{ item }} -t /home/{{ ansible_user }} -d /home/{{ ansible_user }}/dotfile_source"
  args:
    chdir: "/home/{{ ansible_user }}/dotfile_source"
  loop:
    - btop
    - hypr
    - kitty
    - mako
    - waybar
    - wlogout
    - wofi
  become: false
  register: stow_dotfiles
  changed_when: "'LINK' in stow_dotfiles.stdout or 'RESTOW' in stow_dotfiles.stdout"

- name: remove unwanted session files
  file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/usr/share/wayland-sessions/hyprland-uwsm.desktop"
