---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - kitty
      - hyprland           # Wayland compositor
      - waybar             # Status bar
      - wofi               # App launcher
      - grim               # Screenshot tool (captures screen)
      - slurp              # Screenshot tool (selects region)
      - thunar             # File manager
      - btop               # Resource monitor
      - qt5-wayland        # Qt5 Wayland support
      - qt6-wayland        # Qt6 Wayland support
      - xdg-desktop-portal-hyprland # Portal for Hyprland (needed by apps)
      - mpv                # Media player
      - blueman            # Bluetooth manager
      - xorg-xwayland      # Compatibility layer for Xorg applications
      - pamixer            # For audio control
      - mako               # Notification daemon
      - cliphist           # Clipboard history
      - pavucontrol        # PulseAudio/PipeWire volume control
      - gnome-keyring      # provides gnome-keyring-daemon
      - libsecret          # library for accessing secret service api (used by gnome-keyrings)
      - seahorse           # gui to mangage keyrings
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
    yay -S --noconfirm wlogout
    yay -S --noconfirm swww
  become: false

- name: create config directories
  file:
    path: "/home/{{ target_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ target_user }}/.config/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"
