---
# hyprland setup

- name: install hyprland related packages
  pacman:
    name:
      - hyprland
      - waybar
      - wofi
      - grim
      - slurp
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - mako
      - cliphist
      - gnome-keyring
      - libsecret
      - seahorse
    state: present
    extra_args: "--noconfirm"

- name: install hyprland related yay packages
  shell: |
    yay -S --noconfirm grimblast-git
    yay -S --noconfirm light
    yay -S --noconfirm wlogout
    yay -S --noconfirm swww
  become: false

- name: create config directories
  file:
    path: "/home/{{ target_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ target_user }}/.config/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"
