---
# gnome setup

- name: install gnome packages
  pacman:
    name:
      - gnome
      - gnome-tweaks
      - gnome-shell-extensions
      - gdm
      - dconf-editor
      - xdg-desktop-portal-gnome
      - gnome-disk-utility
      - gnome-keyring
      - libsecret
      - seahorse
    state: present
    extra_args: "--noconfirm"
    
- name: create config directories
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"

- name: disable and stop gdm service
  systemd:
    name: gdm.service
    enabled: no
    state: stopped
    masked: yes # don't accidentally enable
  become: true

- name: set dark modea
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
    scope: user
  become: false