---
# gnome setup

- name: install gnome packages
  pacman:
    name:
      - gnome-shell
      - gdm
      - gnome-tweaks
      - gnome-shell-extensions
      - dconf-editor
      - xdg-desktop-portal-gnome
      - gnome-disk-utility
      - gnome-keyring
      - libsecret
      - seahorse
    state: present
    extra_args: "--noconfirm"
  become: true

# only keep wayland-sessions/gnome-wayland.desktop
- name: remove unwanted session files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "/usr/share/xsessions/gnome.desktop"
    - "/usr/share/xsessions/gnome-xorg.desktop"
    - "/usr/share/xsessions/gnome-classic.desktop"
    - "/usr/share/wayland-sessions/gnome.desktop"
    - "/usr/share/wayland-sessions/gnome-classic.desktop"
    - "/usr/share/wayland-sessions/gnome-classic-wayland.desktop"

- name: create config directories
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"

- name: disable and stop gdm service
  systemd:
    name: gdm.service
    enabled: no
    state: stopped
    masked: yes # don't accidentally enable
  become: true

- name: set dark modea
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
    scope: user
  become: false