---
# general configuration
- name: ensure pacman mirrors are updated
  pacman:
    update_cache: yes
    upgrade: yes
    extra_args: "--noconfirm"

- name: enable multilib
  blockinfile:
    path: /etc/pacman.conf
    block: | 
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    state: present
    backup: yes
  become: true

- name: resync pacman
  ansible.builtin.pacman:
    update_cache: yes
  become: true

- name: install common packages
  pacman:
    name:
      - vim
      - wget
      - unzip
      - make
      - linux-headers
      - mesa-utils
      - htop             # Process viewer
      - ufw              # Firewall
      - networkmanager   # Ensure it's installed (should be from pacstrap)
      - pipewire         # audio server
      - wireplumber      # Session manager for PipeWire
      - pipewire-alsa    # ALSA compatibility
      - pipewire-pulse   # PulseAudio compatibility
      - pipewire-jack    # JACK compatibility
      - xdg-utils        # Essential for opening links/files
      - bluez            # Bluetooth stack
      - bluez-utils      # Bluetooth utilities
      - sddm             # Display manager
      - noto-fonts       # General font support
      - ttf-dejavu       # Common font
      - ttf-liberation   # Common font
      - ttf-font-awesome # For icons in status bars
      - nerd-fonts       
      - rsync            # For efficient file syncing
      - base-devel       # Ensures build tools are present (should be from install.sh)
      - sddm
      - qt6-svg
      - qt6-declarative
      - qt5-quickcontrols2
    state: present
    extra_args: "--noconfirm"

- name: install gpu drivers
  pacman:
    name: "{{ gpu_packages }}"
    state: present
  become: true

- name: blacklist nouveau driver
  copy:
    content: | 
      blacklist nouveau
      options nouveau modset=0
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Rebuild initramfs

- name: install configured pacman packages
  pacman:
    name: "{{ pacman_packages }}"
    state: present
    extra_args: "--noconfirm"

- name: install configured yay packages
  shell: |
    yay -S --noconfirm {{ item }}
  become: false
  loop: "{{ yay_packages }}"

- name: enable and start networkmanager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  
- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
  notify: Restart UFW

- name: allow ssh through Firewall
  ufw:
    rule: allow
    port: '22'
    proto: tcp
    state: enabled
  notify: Restart UFW

- name: set time-sync
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started

- name: create config directories
  file:
    path: "/home/{{ target_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ target_user }}/.config/{{ item.path }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"

- name: ensure sddm themes directory exists
  file:
    path: /usr/share/sddm/themes
    state: directory
    mode: '0755'

- name: download catpuccin sddm theme
  get_url: 
    url: https://github.com/catppuccin/sddm/releases/download/v1.0.0/catppuccin-frappe.zip
    dest: "/tmp/catpuccin-frappe.zip"
    mode: '0644'
  become: true

- name: unzip theme to themes directory
  unarchive:
    src: /tmp/catpuccin-frappe.zip
    dest: /usr/share/sddm/themes/
    remote_src: yes
    creates: /usr/share/sddm/themes/catpuccin-frappe

- name: create sddm config
  template:
    src: sddm.conf
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: '0644'

- name: enable and start sddm
  systemd:
    name: sddm.service
    enabled: yes
    state: stopped