---
# general configuration
- name: ensure pacman mirrors are updated
  pacman:
    update_cache: yes
    upgrade: yes
    extra_args: "--noconfirm"

- name: enable multilib
  blockinfile:
    path: /etc/pacman.conf
    block: | 
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    state: present
    backup: yes
  become: true

- name: resync pacman
  ansible.builtin.pacman:
    update_cache: yes
  become: true

- name: install common packages
  pacman:
    name:
      # util
      - vim
      - wget
      - unzip
      - make
      - htop
      - ufw
      - networkmanager
      - xdg-utils
      - rsync
      - base-devel
      - linux-headers
      - mesa-utils
      - smbclient
      - stow

      # audio
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pavucontrol
      - pamixer

      # bluetooth
      - bluez
      - bluez-utils
      - blueman
      
      # fonts
      - noto-fonts
      - ttf-dejavu
      - ttf-liberation
      - ttf-font-awesome
      - nerd-fonts

      # display manager
      - sddm
      - qt6-svg
      - qt6-declarative
      - qt5-quickcontrols2
      
      # apps
      - kitty
      - eog
      - evince
      - btop
      - mpv
      - file-roller
    state: present
    extra_args: "--noconfirm"

- name: install common yay packages
  shell: |
    yay -S --noconfirm --needed openrgb-git
  become: false

- name: install gpu drivers
  pacman:
    name: "{{ gpu_packages }}"
    state: present
  become: true

- name: blacklist nouveau driver
  copy:
    content: | 
      blacklist nouveau
      options nouveau modset=0
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Rebuild initramfs

- name: install configured pacman packages
  pacman:
    name: "{{ pacman_packages }}"
    state: present
    extra_args: "--noconfirm"

- name: install configured yay packages
  shell: |
    yay -S --noconfirm --needed {{ item }}
  become: false
  loop: "{{ yay_packages }}"

- name: enable and start networkmanager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  
- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
  notify: Restart UFW

- name: allow ssh through Firewall
  ufw:
    rule: allow
    port: '22'
    proto: tcp
    state: enabled
  notify: Restart UFW

- name: set time-sync
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started

- name: clone or pull dotfiles
  git:
    repo: "https://github.com/LucaEggenberg/dotfiles.git"
    dest: /home/{{ ansible_user }}/dotfile_source
    version: main
    single_branch: yes
    update: yes

- name: ensure sddm themes directory exists
  file:
    path: /usr/share/sddm/themes
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: yes
  
- name: symlink sddm config
  file:
    src: "/home/{{ ansible_user }}/dotfile_source/sddm/etc/sddm.conf"
    dest: "/etc/sddm.conf"
    state: link
    force: yes
    owner: root
    group: root
  become: yes

- name: symlink sddm theme
  file:
    src: "/home/{{ ansible_user }}/dotfile_source/sddm-theme/usr/share/sddm/themes/catppuccin-frappe"
    dest: "/usr/share/sddm/themes/catppuccin-frappe"
    state: link
    force: yes
    owner: root
    group: root
  become: yes

- name: enable and start sddm
  systemd:
    name: sddm.service
    enabled: yes
    state: started
