---
- name: configure arch
  hosts: hosts
  become: true
  
  pre_tasks:
    - name: check user permission
      user:
        name: "{{ ansible_user }}"
        groups: "wheel,audio,video,input,storage"
        append: yes
    
  roles:
    - role: common
    - role: hyprland
    - role: gnome

  post_tasks:
    - name: update & cleanup
      pacman:
        update_cache: yes
        upgrade: yes
        force: yes
        extra_args: "--noconfirm"
      become: true

    - name: reboot if needed
      ansible.builtin.reboot:
        reboot_timeout: 300
      when:
        - ansible_connection != 'local'