---
- name: configure arch
  hosts: hosts
  become: true
  vars:
    desktop_environment: hyprland # future
  
  pre_tasks:
    - name: check user permission
      user:
        name: "{{ target_user }}"
        groups: "wheel,audio,video,input,storage"
        append: yes
      when: desktop_environment is defined
    
  roles:
    - role: common
    - role: hyprland
      when: desktop_environment == 'hyprland'
    # - role: kde
    #   when: desktop_environment == 'kde'
    # - role: gnome
    #   when: desktop_environment == 'gnome'

  post_tasks:
    - name: update & cleanup
      pacman:
        update_cache: yes
        upgrade: yes
        force: yes
        extra_args: "--noconfirm"
    
    - name: gather orphaned packages
      command: pacman -Qtdq
      register: orphaned_packages
      changed_when: false
      failed_when: orphaned_packages.rc != 0 and "no packages were found" not in orphaned_packages.stderr
      become: true

    - name: remove orphaned packages
      pacman:
        name: "{{ orphaned_packages }}"
        state: absent
        extra_args: "--noconfirm -Rs"
      when: orphaned_packages.stdout_lines | length > 0
      become: true

    - name: reboot if needed
      ansible.builtin.reboot:
      when: desktop_environment is defined and desktop_environment != 'none'