---
# kde setup

- name: install kde packages
  pacman:
    name:
      - plasma-meta
      - kde-utilities-meta
      - kde-system-meta
      - kde-network-meta
    state: present
    extra_args: "--noconfirm"
  become: true

- name: create config directories
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_filetree: "../templates/.config"
  when: item.state == "directory"

- name: Render and copy dotfiles
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/.config/{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_filetree: "../templates/.config"
  when: item.state == "file"